iceflow:
  iceflow: # temporarly mirroring the code but would recommend just cateogorizing the prameters that make sense (i.e. network params, retrain, paths, etc.)
    iflo_run_pretraining: False
    iflo_run_data_assimilation: False
    iflo_type: "emulated"
    iflo_pretrained_emulator: True
    iflo_emulator: ""
    iflo_init_slidingco: 0.0464
    iflo_init_arrhenius: 78
    iflo_enhancement_factor: 1.0
    iflo_regu_glen: 10 ** (-5)
    iflo_regu_weertman: 10 ** (-10)
    iflo_exp_glen: 3
    iflo_exp_weertman: 3
    iflo_gravity_cst: 9.81
    iflo_ice_density: 910
    iflo_new_friction_param: True
    iflo_save_model: False
    iflo_Nz: 10
    iflo_vert_spacing: 4.0
    iflo_thr_ice_thk: 0.1
    iflo_solve_step_size: 1
    iflo_solve_nbitmax: 100
    iflo_solve_stop_if_no_decrease: True
    iflo_fieldin: ["thk", "usurf", "arrhenius", "slidingco", "dX"]
    iflo_dim_arrhenius: 2
    iflo_retrain_emulator_freq: 10
    iflo_retrain_emulator_lr: 0.00002
    iflo_retrain_emulator_nbit_init: 1
    iflo_retrain_emulator_nbit: 1
    iflo_retrain_emulator_framesizemax: 750
    iflo_multiple_window_size: 0
    iflo_force_max_velbar: 0
    iflo_network: "cnn"
    iflo_activation: "LeakyReLU"
    iflo_nb_layers: 16
    iflo_nb_blocks: 4
    iflo_nb_out_filter: 32
    iflo_conv_ker_size: 3
    iflo_dropout_rate: 0
    iflo_weight_initialization: "glorot_uniform"
    iflo_exclude_borders: 0
    iflo_cf_eswn: []
    iflo_cf_cond: False
    iflo_regu: 0.0
    iflo_min_sr: 10**(-20)
    iflo_max_sr: 10**(20)
    iflo_force_negative_gravitational_energy: False
    iflo_optimizer_solver: 'Adam'
    iflo_optimizer_lbfgs: False
    iflo_optimizer_emulator: 'Adam'
    iflo_save_cost_emulator: ""
    iflo_save_cost_solver: ""
    iflo_output_directory: ""
  optimize:
    opti_vars_to_save:
        - "usurf"
        - "thk"
        - "slidingco"
        - "velsurf_mag"
        - "velsurfobs_mag"
        - "divflux"
        - "icemask"
    opti_init_zero_thk: "False"
    opti_regu_param_thk: 10.0
    opti_regu_param_slidingco: 1
    opti_regu_param_arrhenius: 10.0
    opti_regu_param_div: 1
    opti_smooth_anisotropy_factor: 0.2
    opti_smooth_anisotropy_factor_sl: 1.0
    opti_convexity_weight: 0.002
    opti_convexity_power: 1.3
    opti_usurfobs_std: 2.0
    opti_velsurfobs_std: 1.0
    opti_thkobs_std: 3.0
    opti_divfluxobs_std: 1.0
    opti_divflux_method: "upwind"
    opti_force_zero_sum_divflux: "False"
    opti_scaling_thk: 2.0
    opti_scaling_usurf: 0.5
    opti_scaling_slidingco: 0.0001
    opti_scaling_arrhenius: 0.1
    opti_control: ["thk"]
    opti_cost: ["velsurf", "thk", "icemask"]
    opti_nbitmin: 50
    opti_nbitmax: 500
    opti_step_size: 1
    opti_step_size_decay: 0.9
    opti_output_freq: 50
    opti_save_result_in_ncdf: "geology-optimized.nc"
    opti_plot2d_live: True
    opti_plot2d: True
    opti_save_iterat_in_ncdf: True
    opti_editor_plot2d: "vs"
    opti_uniformize_thkobs: True
    sole_mask: False
    opti_retrain_iceflow_model: True
    opti_to_regularize: 'topg'
    opti_include_low_speed_term: False
    opti_infer_params: False
    opti_tidewater_glacier: False
    opti_vol_std: 1000.0
    fix_opti_normalization_issue: False
  pretraining:
    data_dir: "surflib3d_shape_100"
    batch_size: 1
    freq_test: 20
    train_iceflow_emulator_restart_lr: 2500
    epochs: 5000
    min_arrhenius: 5
    max_arrhenius: 151
    min_slidingco: 0
    max_slidingco: 20000
    min_coarsen: 0
    max_coarsen: 2
    soft_begining: 500












