iceflow:
  iceflow:
    run_pretraining: False
    run_data_assimilation: False
    type: "emulated"
    pretrained_emulator: True
    emulator: ""
    init_slidingco: 0.0464
    init_arrhenius: 78.0
    enhancement_factor: 1.0
    regu_glen: 1.0e-5
    regu_weertman: 1.0e-10
    exp_glen: 3.0
    exp_weertman: 3.0
    gravity_cst: 9.81
    ice_density: 910.0
    new_friction_param: True
    save_model: False
    Nz: 10
    vert_spacing: 4.0
    thr_ice_thk: 0.1
    solve_step_size: 1.0
    solve_nbitmax: 100
    solve_stop_if_no_decrease: True
    fieldin: ["thk", "usurf", "arrhenius", "slidingco", "dX"]
    dim_arrhenius: 2
    retrain_emulator_freq: 10
    retrain_emulator_lr: 0.00002
    retrain_emulator_lr_init: 0.0001
    retrain_warm_up_it: -1.0e+10
    retrain_emulator_nbit_init: 1
    retrain_emulator_nbit: 1
    retrain_emulator_framesizemax: 750
    multiple_window_size: 0
    force_max_velbar: 0.0
    network: "cnn"
    activation: "LeakyReLU"
    nb_layers: 16
    nb_blocks: 4
    nb_out_filter: 32
    conv_ker_size: 3
    dropout_rate: 0
    weight_initialization: "glorot_uniform"
    exclude_borders: 0
    cf_eswn: []
    cf_cond: False
    regu: 0.0
    min_sr: 1.0e-20
    max_sr: 1.0e+20
    force_negative_gravitational_energy: False
    optimizer_solver: 'Adam'
    optimizer_lbfgs: False
    optimizer_emulator: 'Adam'
    optimizer_emulator_clipnorm: 1.0e+10
    optimizer_emulator_epsilon: 1.0e-07
    save_cost_emulator: ""
    save_cost_solver: ""
    output_directory: ""
  optimize:
    vars_to_save:
        - "usurf"
        - "thk"
        - "slidingco"
        - "velsurf_mag"
        - "velsurfobs_mag"
        - "divflux"
        - "icemask"
    init_zero_thk: False
    regu_param_thk: 10.0
    regu_param_slidingco: 1.0
    regu_param_arrhenius: 10.0
    regu_param_div: 1.0
    smooth_anisotropy_factor: 0.2
    smooth_anisotropy_factor_sl: 1.0
    convexity_weight: 0.002
    convexity_power: 1.3
    usurfobs_std: 2.0
    velsurfobs_std: 1.0
    thkobs_std: 3.0
    divfluxobs_std: 1.0
    divflux_method: "upwind"
    force_zero_sum_divflux: False
    scaling_thk: 2.0
    scaling_usurf: 0.5
    scaling_slidingco: 0.0001
    scaling_arrhenius: 0.1
    control: ["thk"]
    cost: ["velsurf", "thk", "icemask"]
    nbitmin: 50
    nbitmax: 500
    step_size: 1.0
    step_size_decay: 0.9
    output_freq: 50
    save_result_in_ncdf: "geology-optimized.nc"
    plot2d_live: True
    plot2d: True
    save_iterat_in_ncdf: True
    editor_plot2d: "vs"
    uniformize_thkobs: True
    sole_mask: False
    retrain_iceflow_model: True
    to_regularize: 'topg'
    include_low_speed_term: False
    infer_params: False
    tidewater_glacier: False
    vol_std: 1000.0
    fix_opti_normalization_issue: False
    velsurfobs_thr: 0.0
    log_slidingco: False
  pretraining:
    data_dir: "surflib3d_shape_100"
    batch_size: 1
    freq_test: 20
    train_iceflow_emulator_restart_lr: 2500
    epochs: 5000
    min_arrhenius: 5.0
    max_arrhenius: 151.0
    min_slidingco: 0.0
    max_slidingco: 20000.0
    min_coarsen: 0
    max_coarsen: 2
    soft_begining: 500