- Name: filename
  Description: "NetCDF input data file"
  Units: file path
- Name: coarsening.boundary
  Description: "Method for coarsening the data from NetCDF file: skipping or cubic_spline"
  Units: string
- Name: coarsening.ratio.x
  Description: "Coarsen ratio x"
  Units: ???
- Name: coarsening.ratio.y
  Description: "Coarsen ratio y"
  Units: ???
- Name: crop.xmin
  Description: "X left coordinate for cropping the NetCDF data"
  Units: float
- Name: crop.xmax
  Description: "X right coordinate for cropping the NetCDF data"
  Units: float
- Name: crop.ymin
  Description: "Y bottom coordinate for cropping the NetCDF data"
  Units: float
- Name: crop.ymax
  Description: "Y top coordinate for cropping the NetCDF data"
  Units: float