type:
  Type: str
  Units: [dimensionless]
  Description: "Type of file to be loaded, can be netcdf or tif"
folder:
  Type: str
  Units: [dimensionless]
  Description: "Folder where the data is stored"
filename:
  Type: str
  Units: [dimensionless]
  Description: "NetCDF input data file"
  
coarsening.boundary:
  Type: str
  Units: [dimensionless]
  Description: "Method for coarsening the data from NetCDF file: skipping or cubic_spline"
coarsening.ratio.x:
  Type: float
  Units: [dimensionless]
  Description: "Coarsen ratio x"
coarsening.ratio.y:
  Type: float
  Units: [dimensionless]
  Description: "Coarsen ratio y" 

crop.xmin:
  Type: float
  Units: $m$
  Description: "X left coordinate for cropping the NetCDF data" 
crop.xmax:
  Type: float
  Units: $m$
  Description: "X right coordinate for cropping the NetCDF data" 
crop.ymin:
  Type: float
  Units: $m$
  Description: "Y bottom coordinate for cropping the NetCDF data" 
crop.ymax:
  Type: float
  Units: $m$
  Description: "Y top coordinate for cropping the NetCDF data" 

icemask.include:
  Type: bool
  Units: [dimensionless]
  Description: Include ice mask in the NetCDF file
icemask.shapefile:
  Type: str
  Units: [dimensionless]
  Description: Shapefile for ice mask
icemask.invert:
  Type: bool
  Units: [dimensionless]
  Description: Invert the ice mask
