cwd: ${get_cwd:0} #0 is a dummy input since resolvers require callables

core:
  # Input / Output
  saved_params_filename: params_saved
  url_data: ""
  folder_data: data
  logging_file: ""

  # Logging
  logging: False
  logging_level: 30

  # Hardware
  gpu_id: 0
  gpu_info: True

  # Misc
  print_params: True

defaults:
  - _self_
  - modules:
    - load_ncdf # ths should not be a module...
    - smb_simple
    - iceflow
    - time_igm # ths should not be a module...
    - thk
    - print_info # this should not be a module...
    # - oggm_shop
  # - params@_here_ # is this necessary with experiment? No !
    # - plot2d

hydra:
  searchpath:
    - file:///${cwd} # adds cwd to the search path

