cwd: ${get_cwd:0} #0 is a dummy input since resolvers require callables
# cwd: ${hydra.runtime.cwd} # do I need a custom resolver or can I just access the cwd from hydra?

# core:
#   # Input / Output
#   saved_params_filename: params_saved
#   url_data: ""
#   folder_data: data
#   logging_file: ""

#   # Logging
#   logging: False
#   logging_level: 30

#   # Hardware
#   gpu_id: 0
#   gpu_info: True

#   # Misc
#   print_params: True

# ! Problem
# We need to start with NO modules such that if a user specifies a module and just one change, it will load it and then overwrite it.
# If we do not load the module beforehand, it will create a new module and not overwrite the existing one...

defaults:
  - _self_
  - core
  - modules: null
    # - load_ncdf # ths should not be a module...
    # - smb_simple
    # - iceflow
    # - time_igm # ths should not be a module...
    # - thk
  #   - print_info # this should not be a module...
    # - oggm_shop
  # - params@_here_ # is this necessary with experiment? No !
    # - plot2d

hydra:
  searchpath:
    - file:///${cwd} # adds cwd to the search path

